from app.visualizers.draw import (
    bars,
    blobs,
    circular,
    flame,
    grid_pulse,
    kaleidoscope,
    matrix,
    mirror_wave,
    orbits,
    particles,
    radial,
    ring_tunnel,
    scope3d,
    spiral,
    terrain,
    warp,
    waveform,
)

VISUALIZERS = [
    {"id": "bars", "name": "Bars", "draw": bars, "fade": 0.18},
    {"id": "circular", "name": "Circular", "draw": circular, "fade": 0.15},
    {"id": "waveform", "name": "Waveform", "draw": waveform, "fade": 0.22},
    {"id": "mirror", "name": "Mirror", "draw": mirror_wave, "fade": 0.2},
    {"id": "radial", "name": "Radial", "draw": radial, "fade": 0.14},
    {"id": "particles", "name": "Particles", "draw": particles, "fade": 0.08},
    {"id": "spiral", "name": "Spiral", "draw": spiral, "fade": 0.12},
    {"id": "kaleido", "name": "Kaleido", "draw": kaleidoscope, "fade": 0.1},
    {"id": "grid", "name": "Grid", "draw": grid_pulse, "fade": 0.25},
    {"id": "flame", "name": "Flame", "draw": flame, "fade": 0.06},
    {"id": "matrix", "name": "Matrix", "draw": matrix, "fade": 0.15},
    {"id": "orbits", "name": "Orbits", "draw": orbits, "fade": 0.12},
    {"id": "blobs", "name": "Blobs", "draw": blobs, "fade": 0.1},
    {"id": "warp", "name": "Warp", "draw": warp, "fade": 0.2},
    {"id": "terrain", "name": "Terrain", "draw": terrain, "fade": 0.18},
    {"id": "tunnel", "name": "Tunnel", "draw": ring_tunnel, "fade": 0.12},
    {"id": "scope3d", "name": "3D Scope", "draw": scope3d, "fade": 0.15},
]
